# Site settings
author: Ally Netzel
title: Ally
header-img: img/umbrella.png
email: netzelally@gmail.com
copyright_name: Ally Netzel
description: > # this means to ignore newlines until "baseurl:"
 Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  netzay

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
